FROM registry.fedoraproject.org/fedora:36

RUN mkdir -p /home/share/iso && \
    mkdir -p /var/log/samba

RUN set -x && \
    dnf -y update && \
    dnf install -y samba && \
    dnf clean all && \
    rm -rf /var/cache/yum /var/cache/dnf

COPY smb.conf /etc/samba/

WORKDIR /home/share/

RUN chown -R 1024 /home/share/ && \
    chown -R 1024 /var/log/samba/ && \
    chown -R 1024 /etc/samba/

USER 1024

ENTRYPOINT ["/usr/sbin/smbd", "-s", "/etc/samba/smb.conf", "-F"] 
