FROM registry.fedoraproject.org/fedora:latest

RUN mkdir -p /srv/public/iso

RUN set -x && \
    dnf -y update && \
    dnf install -y samba && \
    dnf clean all && \
    rm -rf /var/cache/yum /var/cache/dnf

COPY smb.conf /etc/samba/smb.conf

WORKDIR /srv/public/

RUN chmod -R 777 /var/log/samba && \
    chmod 777 /etc/samba/smb.conf && \
    chmod -R 777 /srv/public/

RUN chown -R 1024 /srv/public/

USER 1024

ENTRYPOINT ["/usr/sbin/smbd", "-F", "--no-process-group", "-s", "/etc/samba/smb.conf"]