---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: fakefish
  name: fakefish
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  namespace: fakefish
  name: samba-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-for-samba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: samba-sa
  namespace: fakefish
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samba-server
  name: samba-server
  namespace: fakefish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samba-server
    spec:
      serviceAccount: samba-sa
      serviceAccountName: samba-sa
      containers:
      - image: docker.io/dperson/samba
        args:
        - -p
        - -s ISOS;/isos;yes;yes;yes
        name: samba
        resources: {}
        ports:
        - containerPort: 139
          protocol: TCP
        - containerPort: 445
          protocol: TCP
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /isos
          name: smb-volume
      - image: busybox
        command:
        - /bin/sh
        - -c
        - sleep 100000000
        name: busybox
        resources: {}
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /isos
          name: smb-volume
        - mountPath: /custom-scripts
          name: custom-scripts
      - image: quay.io/mavazque/fakefish:hpe
        args:
        - --listen-port=9000
        - --tls-mode=disabled
        - --remote-bmc=172.20.10.10
        name: fakefish
        resources: {}
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http-9000
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /isos
          name: smb-volume
        - mountPath: /opt/fakefish/custom_scripts
          name: custom-scripts
      volumes:
      - name: smb-volume
        emptyDir: {}
      - name: custom-scripts
        configMap:
          name: custom-scripts
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: samba-server
  namespace: fakefish
  labels:
    name: samba-server
spec:
  type: NodePort
  ports:
  - port: 139
    nodePort: 31139
    name: port-139
  - port: 445
    name: port-445
    nodePort: 31445
  selector:
    app: samba-server
